# Generated by Django 3.2.2 on 2021-06-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLibro',
            fields=[
                ('idCatLibro', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('catLibro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idIsbn', models.AutoField(primary_key=True, serialize=False)),
                ('nomLibro', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('tipoLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorialibro')),
            ],
        ),
    ]
