# Generated by Django 3.2.2 on 2021-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorialibro',
            name='idCatLibro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='idIsbn',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
