# Generated by Django 3.2.2 on 2021-06-17 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210616_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='tipoLibro',
        ),
        migrations.AddField(
            model_name='libro',
            name='categorialibro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categorialibro'),
        ),
    ]
