# Generated by Django 3.2.3 on 2021-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210616_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idHab', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('canCama', models.CharField(max_length=50)),
                ('CanBanno', models.CharField(max_length=50)),
                ('CanPers', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='Habitaciones')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('cantHab', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='comentario',
        ),
    ]
