# Generated by Django 3.2.3 on 2021-07-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210703_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('idHotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombreh', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasenia',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='inventario',
            name='servicios',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipHab',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='canHabi',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='canPer',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.habitacion'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hotel'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hotel'),
        ),
    ]
