# Generated by Django 3.2.3 on 2021-07-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210704_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dia',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
