# Generated by Django 3.2.3 on 2021-07-05 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('idCentro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('canP', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('dispo', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
    ]
