# Generated by Django 4.0.3 on 2022-06-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_centro_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idMed', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('gramaje', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fechaVen', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes')),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('idPres', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAp', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('cantidadMed', models.IntegerField()),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='centro',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='categorialibro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='CategoriaLibro',
        ),
        migrations.DeleteModel(
            name='Centro',
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
