# Generated by Django 4.0.3 on 2022-06-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medicamento_prescripcion_remove_centro_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='contenido',
            field=models.CharField(blank=True, default='Some String', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fabricante',
            field=models.CharField(blank=True, default='Some String', max_length=50, null=True),
        ),
    ]
