# Generated by Django 4.0.3 on 2022-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medicamento_contenido_medicamento_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
