# Generated by Django 4.0.3 on 2022-06-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_caducar'),
    ]

    operations = [
        migrations.AddField(
            model_name='caducar',
            name='codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicamento'),
        ),
        migrations.AlterField(
            model_name='caducar',
            name='medicamento',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caducar',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
