# Generated by Django 4.0.3 on 2022-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_caducar_codigo_alter_caducar_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caducar',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
