# Generated by Django 4.0.3 on 2022-06-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_prescripcion_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescripcion',
            name='medicamento',
        ),
    ]
