# Generated by Django 4.0.3 on 2022-06-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_prescripcion_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('idMen', models.AutoField(primary_key=True, serialize=False)),
                ('nombreApe', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('medicamento', models.CharField(max_length=100)),
            ],
        ),
    ]
