# Generated by Django 4.0.3 on 2022-06-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_mensajeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='codigo',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
