# Generated by Django 4.0.3 on 2022-06-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_mensajeria_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='cantidad',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
