# Generated by Django 4.0.3 on 2022-06-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_mensajeria_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeria',
            name='codigo',
        ),
    ]
