# Generated by Django 4.0.3 on 2022-06-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_mensajeria_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('idRet', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=100)),
            ],
        ),
    ]
