# Generated by Django 4.2.1 on 2023-05-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_prescripcion_retira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
    ]
