# Generated by Django 4.2.1 on 2023-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_producto_delete_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('idMotivo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('productoEliminado', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Caducar',
        ),
        migrations.DeleteModel(
            name='Prescripcion',
        ),
        migrations.DeleteModel(
            name='Retiro',
        ),
    ]
