# Generated by Django 4.2.1 on 2023-05-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_inventario_tienda_remove_producto_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='idTienda',
            new_name='tienda',
        ),
    ]
