# Generated by Django 4.2.1 on 2023-05-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_inventario_producto_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('inventarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventario')),
            ],
        ),
    ]
