# Generated by Django 4.2.1 on 2023-05-26 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoSolicitud',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('estadoSol', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fechaSolicitud',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='inventarioId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estadoSol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estadosolicitud'),
        ),
    ]
