# Generated by Django 4.2.1 on 2023-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_estadosolicitud_solicitud_fechasolicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='respuesta',
            field=models.CharField(default=-2000, max_length=50),
            preserve_default=False,
        ),
    ]
