# Generated by Django 4.2.1 on 2023-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_solicitud_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_producto',
            name='compartimiento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario_producto',
            name='estante',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='imagenTienda',
            field=models.ImageField(null=True, upload_to='Tiendas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Productos'),
        ),
    ]
