# Generated by Django 4.2.1 on 2023-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_motivo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockProducto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
